import { GameObjectType } from "./gameObject"

export const ObjectColors = {
  [GameObjectType.Player]: "#44E",
  [GameObjectType.Enemy]: "#E44",
  [GameObjectType.ExperienceOrb]: "#8c8",
  [GameObjectType.Bullet]: "#aaaa",
}

export const ItemData = {
  weapons: [
    {
      name: "Pistol",
      description: "A pistol",
      damage: 8,
      critChance: 0.1,
      critMultiplier: 2,
      bulletSpeed: 10,
      bulletRange: 500,
      bulletWeight: 6,
      bulletCooldown: 500,
      numBullets: 1,
      bulletSize: 3,
    },
    {
      name: "Shotgun",
      description: "A shotgun",
      damage: 5,
      critChance: 0.1,
      critMultiplier: 2,
      bulletSpeed: 10,
      bulletRange: 200,
      bulletWeight: 6,
      bulletCooldown: 1000,
      numBullets: 5,
      bulletSize: 3,
    },
    {
      name: "Rifle",
      description: "A rifle",
      damage: 15,
      critChance: 0.1,
      critMultiplier: 2,
      bulletSpeed: 10,
      bulletRange: 500,
      bulletWeight: 6,
      bulletCooldown: 200,
      numBullets: 1,
      bulletSize: 5,
    },
    {
      name: "Sniper",
      description: "A sniper",
      damage: 20,
      critChance: 0.1,
      critMultiplier: 2,
      bulletSpeed: 10,
      bulletRange: 500,
      bulletWeight: 6,
      bulletCooldown: 200,
      numBullets: 1,
      bulletSize: 5,
    },
    {
      name: "Machine Gun",
      description: "A machine gun",
      damage: 4,
      critChance: 0.1,
      critMultiplier: 2,
      bulletSpeed: 10,
      bulletRange: 500,
      bulletWeight: 6,
      bulletCooldown: 100,
      numBullets: 1,
      bulletSize: 3,
    },
    {
      name: "Minigun",
      description: "A minigun",
      damage: 5,
      critChance: 0.1,
      critMultiplier: 2,
      bulletSpeed: 10,
      bulletRange: 500,
      bulletWeight: 6,
      bulletCooldown: 200,
      numBullets: 1,
      bulletSize: 2,
    },
    {
      name: "Rocket Launcher",
      description: "A rocket launcher",
      damage: 5,
      critChance: 0.1,
      critMultiplier: 2,
      bulletSpeed: 10,
      bulletRange: 500,
      bulletWeight: 6,
      bulletCooldown: 200,
      numBullets: 1,
      bulletSize: 15,
    },
    {
      name: "Grenade Launcher",
      description: "A grenade launcher",
      damage: 5,
      critChance: 0.1,
      critMultiplier: 2,
      bulletSpeed: 10,
      bulletRange: 500,
      bulletWeight: 6,
      bulletCooldown: 200,
      numBullets: 1,
      bulletSize: 15,
    },
    {
      name: "Flamethrower",
      description: "A flamethrower",
      damage: 5,
      critChance: 0.1,
      critMultiplier: 2,
      bulletSpeed: 10,
      bulletRange: 500,
      bulletWeight: 6,
      bulletCooldown: 200,
      numBullets: 8,
      bulletSize: 15,
    },
  ],
  helmets: [
    {
      name: "Raggedy Helmet",
      description: "A pretty shit helmet",
      armor: 2,
    },
    {
      name: "Leather Helmet",
      description: "An average helmet",
      armor: 5,
    },
  ],
  gloves: [
    {
      name: "Raggedy Gloves",
      description: "Some pretty shite gloves",
      armor: 1,
    },
    {
      name: "Leather Gloves",
      description: "An average pair of gloves",
      armor: 3,
    },
  ],
  armor: [
    {
      name: "Raggedy Armor",
      description: "A pretty shite armor",
      armor: 1,
    },
    {
      name: "Leather Armor",
      description: "An average armor",
      armor: 3,
    },
  ],
  boots: [
    {
      name: "Raggedy Boots",
      description: "Some pretty shite boots",
      armor: 1,
    },
    {
      name: "Leather Boots",
      description: "An average pair of boots",
      armor: 3,
    },
  ],
  belt: [
    {
      name: "Raggedy Belt",
      description: "A pretty shite belt",
      armor: 1,
    },
    {
      name: "Leather Belt",
      description: "An average belt",
      armor: 3,
    },
  ],
  ring: [],
} as const
